version: "3.1"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    # networks:
    #   - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    # networks: 
    #  - network-backend
  
  mongo:
    image: mongo
    restart: always
    # volumes: 
    #   - ./mongodb/data:/data/db
      #- mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
    # uncomment following lines to access db locally
    # ports:
    #   - "27017:27017"
    # networks: 
    #  - network-backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    # networks: 
    #  - network-backend

# networks:
#   network-backend:

# volumes: 
#   mongodb_data:
